# Generated by Django 4.2.20 on 2025-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
