# Generated by Django 4.2.20 on 2025-04-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
